### ISSUE TITLE
AttributeError: 'EnumTypeWrapper' object has no attribute 'INPUT'

### ISSUE THREAD

**Issue by kareefardi** [google/bigspicy#20] opened 2022-08-28 16:42 UTC
## Expected Behavior
For the script to go beyond the import statments

## Actual Behavior
```
  File "./bigspicy.py", line 24, in <module>
    import circuit_writer
  File "/media/karim/Elements/work/bigspicy/circuit_writer.py", line 24, in <module>
    class CircuitWriter():
  File "/media/karim/Elements/work/bigspicy/circuit_writer.py", line 27, in CircuitWriter
    circuit.Port.Direction.INPUT: circuit_pb.Port.Direction.INPUT,
AttributeError: 'EnumTypeWrapper' object has no attribute 'INPUT'
```

## Steps to Reproduce the Problem

1. clone the repo
2. `sudo apt install -y protobuf-compiler iverilog`
3. `pip install -e ".[dev]"`
4. 
```
git submodule update --init   # Make sure we pull from Vlsir/schema-proto the
                              # first time.
protoc --proto_path vlsir vlsir/*.proto vlsir/*/*.proto --python_out=.
protoc proto/*.proto --python_out=.
```
5. run the script with any input output

## Specifications

- Version:
repo version:
```
v0.0.1
```
also happens with latest commit as of this post date
python version:
```
❯ python3 --version
Python 3.8.10
```
- Platform: 
```
Ubuntu 20.04.3 LTS
```

**Comment by growly** [comment] 2022-08-29 23:02
Thanks for the bug report! I cannot reproduce this on my system and would like to understand why. I suspect it's related to the generated protocol buffers.

Could you also please provide:

- which version of protoc you are running (`protoc --version`)
- what input file(s) you used (you mention that _any_ will break it but my examples do not - I'm using `example_inputs/fp_multiplier/fp_multiplier.synth.v`)
- what your cloned `bigspicy` directory looks like after you run the submodule init and protoc generation steps

e.g. I'm running `./bigspicy.py     --import     --verilog example_inputs/fp_multiplier/fp_multiplier.synth.v     --top fp_multiplier     --save final.pb     --working_dir /tmp/bigspicy` with no error.

My `bigspicy` directory immediately after clone, submodule init and protoc invocations:

```
$ tree
.
├── bigspicy.py
├── circuit_pb2.py
├── circuit.py
├── circuit_writer.py
├── design.py
├── docs
│   ├── code-of-conduct.md
│   └── contributing.md
├── example_inputs
│   └── fp_multiplier
│       ├── fp_multiplier.synth.v
│       ├── fp_multiplier_test.v
│       ├── fp_multiplier.v
│       ├── Makefile
│       └── openroad_config
│           ├── fp_multiplier
│           │   ├── config.mk
│           │   ├── constraint.sdc
│           │   └── rules.json
│           └── README.md
├── layout
│   ├── raw_pb2.py
│   └── tetris_pb2.py
├── LICENSE
├── proto
│   ├── circuit_analysis_pb2.py
│   ├── circuit_analysis.proto
│   ├── test_manifest_pb2.py
│   └── test_manifest.proto
├── README.md
├── requirements.txt
├── setup.py
├── spef.py
├── spice_analyser.py
├── spice_pb2.py
├── spice.py
├── spice_util.py
├── tech_pb2.py
├── utils_pb2.py
├── verilog.py
└── vlsir
    ├── circuit.proto
    ├── layout
    │   ├── raw.proto
    │   └── tetris.proto
    ├── LICENSE
    ├── README.md
    ├── spice.proto
    ├── tech.proto
    └── utils.proto
```

**Comment by growly** [comment] 2022-08-29 23:19
I suspect that the problem is that the `setup.py` file does not stipulate a new-enough version of the `protobuf` package. I have updated it and the instructions to use the included `requirements.txt` file instead.

Please re-clone the repo and set up according to the new instructions:

1. clone the repo, and in it:
2. `sudo apt install -y protobuf-compiler iverilog`
3. `pip install -e ".[dev]"`
4. `pip install -r requirements.txt`
5. `git submodule update --init`
6. `protoc --proto_path vlsir vlsir/*.proto vlsir/*/*.proto --python_out=.`
7. `protoc proto/*.proto --python_out=.`

**Comment by growly** [comment] 2022-09-02 20:16
Marking this as closed since, please re-open if problem persists.

**Closed by growly** 2022-09-02 20:16 UTC
